 **PROYECTO** 4 

In [1]:
import numpy as np
import pandas as pd
!pip install wooldridge


     |████████████████████████████████| 5.1 MB 5.3 MB/s 


In [2]:
import wooldridge as wd

In [60]:
crime=wd.data("crime1")

In [5]:
crime=crime[["narr86","pcnv","avgsen","tottime","inc86"]]

In [6]:
crime

narr86  pcnv     avgsen    tottime       inc86
0          0  0.38  17.600000  35.200001    0.000000
1          2  0.44   0.000000   0.000000    0.800000
2          1  0.33  22.799999  22.799999    0.000000
3          2  0.25   0.000000   0.000000    8.800000
4          1  0.00   0.000000   0.000000    8.100000
...      ...   ...        ...        ...         ...
2720       1  0.00   0.000000   0.000000    0.000000
2721       0  0.00   0.000000   0.000000   11.500000
2722       0  0.00   0.000000   0.000000    1.900000
2723       1  0.00   0.000000   0.000000    0.000000
2724       0  0.00   0.000000   0.000000  191.300003

[2725 rows x 5 columns]

In [7]:
y=crime.pop("narr86")

In [8]:
x=np.c_[np.ones(len(crime)),crime.to_numpy()]

In [9]:
x

array([[  1.        ,   0.38      ,  17.60000038,  35.20000076,
          0.        ],
       [  1.        ,   0.44      ,   0.        ,   0.        ,
          0.80000001],
       [  1.        ,   0.33000001,  22.79999924,  22.79999924,
          0.        ],
       ...,
       [  1.        ,   0.        ,   0.        ,   0.        ,
          1.89999998],
       [  1.        ,   0.        ,   0.        ,   0.        ,
          0.        ],
       [  1.        ,   0.        ,   0.        ,   0.        ,
        191.30000305]])

In [10]:
y

0       0
1       2
2       1
3       2
4       1
       ..
2720    1
2721    0
2722    0
2723    1
2724    0
Name: narr86, Length: 2725, dtype: int64

In [11]:
class regresion:
  def __init__(self,x,y):
    self.x=x
    self.y=y
  def betas(self):
    b=np.linalg.inv(x.T@x)@(x.T@y)
    return b

In [12]:
def errorest(h):
  h=(x.T)*betas


In [13]:
x.shape

(2725, 5)

In [14]:
y=y.values.reshape(-1,1)

In [15]:
b=np.linalg.inv(x.T@x)@(x.T@y)

In [16]:
b

array([[ 0.59387489],
       [-0.16243696],
       [-0.00618803],
       [ 0.00771062],
       [-0.00243615]])

In [17]:
yestim=x@b

In [18]:
errorestim=y-yestim

In [38]:
varianza=(errorestim.T@errorestim)

In [25]:
n,k=x.shape 

In [39]:
(varianza*np.linalg.inv(x.T@x)).shape 

(5, 5)

In [27]:
np.diagonal(varianza*np.linalg.inv(x.T@x))

array([1.81864892e+00, 4.53139242e+00, 4.16928520e-01, 2.41978326e-01,
       1.60884674e-04])

In [28]:
errorestandar=(np.diagonal(varianza*np.linalg.inv(x.T@x)))**(1/2)

In [29]:
import statsmodels.api as sm

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [30]:
import statsmodels.api 

In [40]:
res=modelo.fit()

NameError: ignored

In [41]:
import statsmodels.api as sm 

In [42]:
import statsmodels.api 

In [43]:
res=modelo.fit()

NameError: ignored

In [44]:
res.summary()

NameError: ignored

In [45]:
class regresion:
  def __init__(self,x,y):
    self.x=x
    self.y=y
  def betas(self):
    b=np.linalg.inv(self.x.T@self.x)@(self.x.T@self.y)
    return b
  def ee(self):
    errorestandar=(np.diagonal(varianza*np.linalg.inv(self.x.T@self.x)))**(1/2)
    return errorestandar.reshape(-1,1)
  def estadisticot(self):
    estadisticot=((self.betas())/self.ee())
    return estadisticot
  def intervaloconfianza(self):
    limsup=self.betas()+1.96*self.ee()
    liminf=self.betas()-1.96*self.ee()
    for i, j in zip(liminf, limsup):
      print(i[0], j[0])
    #return  liminf, limsup

In [46]:
reg=regresion(x,y)

In [47]:
reg.ee()

array([[1.34857292],
       [2.12870675],
       [0.64570002],
       [0.49191292],
       [0.01268403]])

In [48]:
reg.estadisticot()

array([[ 0.44037284],
       [-0.07630781],
       [-0.00958344],
       [ 0.01567477],
       [-0.19206438]])

In [49]:
reg.intervaloconfianza()

-2.049328035728479 3.237077813741032
-4.334702183522381 4.009828267906169
-1.2717600736885761 1.2593840180731832
-0.9564387103354108 0.9718599550777769
-0.027296854046928214 0.022424552409778815


In [50]:
import wooldridge as wd


In [51]:
crime2=wd.data("crime1")

In [52]:
crime2=crime2[["narr86","pcnv","avgsen","tottime","inc86","pcnvsq","inc86sq"]]

In [53]:
crime2

narr86  pcnv     avgsen    tottime       inc86  pcnvsq       inc86sq
0          0  0.38  17.600000  35.200001    0.000000  0.1444      0.000000
1          2  0.44   0.000000   0.000000    0.800000  0.1936      0.640000
2          1  0.33  22.799999  22.799999    0.000000  0.1089      0.000000
3          2  0.25   0.000000   0.000000    8.800000  0.0625     77.440002
4          1  0.00   0.000000   0.000000    8.100000  0.0000     65.610008
...      ...   ...        ...        ...         ...     ...           ...
2720       1  0.00   0.000000   0.000000    0.000000  0.0000      0.000000
2721       0  0.00   0.000000   0.000000   11.500000  0.0000    132.250000
2722       0  0.00   0.000000   0.000000    1.900000  0.0000      3.610000
2723       1  0.00   0.000000   0.000000    0.000000  0.0000      0.000000
2724       0  0.00   0.000000   0.000000  191.300003  0.0000  36595.691406

[2725 rows x 7 columns]

In [54]:
x=np.c_[np.ones(len(crime2)),crime2.to_numpy()]

In [55]:
x

array([[1.00000000e+00, 0.00000000e+00, 3.79999995e-01, ...,
        0.00000000e+00, 1.44400001e-01, 0.00000000e+00],
       [1.00000000e+00, 2.00000000e+00, 4.39999998e-01, ...,
        8.00000012e-01, 1.93599999e-01, 6.40000045e-01],
       [1.00000000e+00, 1.00000000e+00, 3.30000013e-01, ...,
        0.00000000e+00, 1.08900011e-01, 0.00000000e+00],
       ...,
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        1.89999998e+00, 0.00000000e+00, 3.60999990e+00],
       [1.00000000e+00, 1.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        1.91300003e+02, 0.00000000e+00, 3.65956914e+04]])

In [56]:
y

array([[0],
       [2],
       [1],
       ...,
       [0],
       [1],
       [0]])

In [57]:
def errorest2(h):
  h=(x.T)*betas

In [58]:
def errorest2(h):
  h=(x.T)*betas

In [59]:
x.shape

(2725, 8)

CONCLUSION : Las variables interpretadas, muestran que la cantidad de veces que la persona sea arrestada no teien que ver con el salario, el tiempo que este  pase en prsion no tiene que ver con que vuelva o no a ser encarcelado. 